// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiXxVF1LGtr-Mp2DAmIGTYnBqNZ3wKjLM',
    appId: '1:506948131993:web:0c640cb822b5151d49ac08',
    messagingSenderId: '506948131993',
    projectId: 'tesdsw22',
    authDomain: 'tesdsw22.firebaseapp.com',
    storageBucket: 'tesdsw22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaNCNeNVIggerp5mvIr2tBWIyyIr4PIZU',
    appId: '1:506948131993:android:c557729d26379bd849ac08',
    messagingSenderId: '506948131993',
    projectId: 'tesdsw22',
    storageBucket: 'tesdsw22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwWoGlfdJFGfWPE1b8pTIFrtgLdKMf_gM',
    appId: '1:506948131993:ios:e397ccc0d323a96d49ac08',
    messagingSenderId: '506948131993',
    projectId: 'tesdsw22',
    storageBucket: 'tesdsw22.appspot.com',
    iosBundleId: 'com.katya.conexionfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwWoGlfdJFGfWPE1b8pTIFrtgLdKMf_gM',
    appId: '1:506948131993:ios:1053f0346c308f3049ac08',
    messagingSenderId: '506948131993',
    projectId: 'tesdsw22',
    storageBucket: 'tesdsw22.appspot.com',
    iosBundleId: 'com.katya.conexionfirebase.RunnerTests',
  );
}
